name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: compile stat.c
      run: gcc stat.c -o analysis
    - name: compile encrypt.c
      run: gcc encrypt.c -o encrypt

